spring:
  application.name: OAuth-Server
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true


server.port: 8083

security:
  jwt:
    secret: test
    issuer: localhost
    access-ttl-seconds: 600
    refresh-ttl-seconds: 8600
  cookies:
    refresh-token-name: refreshToken
    is-secure: true
    is-http-only: true
    same-site: lax
    domain: localhost
    path: "/"